var rootBase = document.getElementById('cfgjs');

seajs.config({
	base: rootBase.getAttribute('base'),
	alias: {
		'jquery': 'js/lib/jquery.min.js',
		'cookie': 'js/lib/jquery.cookie.js',
		'pjax': 'js/lib/pjax.jquery.js',
		'AjaxMods': 'js/mods/ajaxmods.js',
		'tree': 'js/mods/tree.js',
		'treehide': 'js/mods/tree.exhide.js',
		'modal': 'js/mods/modal.js',
		'ZeroClipboard': 'js/mods/ZeroClipboard.js',
		'tab': 'js/mods/tab.js',
		'vaild': 'js/mods/validate.js',
		'vaildnormal': 'js/mods/vaildnormal.js',
		'pagination': 'js/mods/pagination.js',
		'dropdown': 'js/mods/dropdown.js',
		'common': 'js/mods/common.js',
		'fileupload': 'js/mods/fileupload',
		'fileuploadie9': 'js/mods/jquery.iframe-transport',
		'webuploader': 'js/mods/webuploader',
		'datepicker': 'js/mods/datepicker.js',
		'Packajax': 'js/mods/packajax.js',
		'popover': 'js/mods/popover.js',
		'controlcachelist': 'js/mods/control.cachelist.js',
		'controlcachearray': 'js/mods/control.cachearray.js',
		'RenderPage': 'js/mods/renderpage.js',
		'core': 'js/lib/core.js',
		'draggable': 'js/lib/draggable.js',
		'droppable': 'js/lib/droppable.js',
		'mouse': 'js/lib/mouse.js',
		'widget': 'js/lib/widget.js',
		'handlebars':'js/lib/handlebars.js',
		'collapse': 'js/mods/collapse.js',
		'treetable': 'js/mods/treetable.js',
		'translate': 'js/mods/translate.js',
		'Deltreetable': 'js/mods/del.treetable.js',
		'checktreetable': 'js/mods/check.treetable.js',
		'Selecttreetable': 'js/mods/select.treetable.js',
		'UpdateNametreetable': 'js/mods/updatename.treetable.js',
		'UpdateUnittreetable': 'js/mods/updateunit.treetable.js',
		'reviewtreetable': 'js/mods/review.treetable.js',
		'Relation': 'js/mods/relation.js',
		'transition': 'js/mods/transition.js',
		'Reduction': 'js/mods/reduction.treetable.js',
		'fullbox': 'js/mods/drag.fullbox.js',
		'drawback': 'js/mods/drag.drawback.js',
		'filterTable': 'js/mods/filter.table.js',
		'setvarTable': 'js/mods/setvar.table.js',
		'spectrum': 'js/mods/spectrum.js',
		'myTips':'js/plugin/tips/js/tips.js',
		'draw': 'js/func/book/chart/draw.js',
		'JSON2': 'js/lib/json2.js',
		'echarts': 'js/mods/echarts.js',
		'jqueryTips': 'js/mods/jquery.tips.js',
		'queryLockTable':'js/mods/QuerylockTable.js',
		'debounce':'js/mods/jquery.ba-throttle-debounce.js',
		'drawview': 'js/func/advquery/drag/drawview.js',
		'dragwidth': 'js/mods/drag.width.js',
		'CombinFormattreetable':'js/mods/CombinFormat.treetable.js',
		'semantic':'js/lib/semantic.components.js',
		'uidropdown':'js/lib/semantic.components.uidropdown.js',
		"area": "js/view/area.js",
        "figures": "js/view/figures.js",
        "check": "js/view/check.js",
        "tools": "js/view/tools.js",
        "excel": "js/view/excel.js",
        "alert": "js/mods/alert.js",
        "publicfn": "js/mods/public.fn.js",
		'synonym':'js/func/metadata/zbmgr/synonym.js',
		'dropList': 'js/lib/dropList.js'
	}
})